
F:\code\python\hand_writing>python sv4++.py
Using TensorFlow backend.
2019-04-20 02:41:06.554519: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-04-20 02:41:06.706850: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.695
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.63GiB
2019-04-20 02:41:06.726577: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-20 02:41:07.404278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-20 02:41:07.418650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-04-20 02:41:07.425087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-04-20 02:41:07.433947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6380 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:From C:\Program Files\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-04-20 02:41:07.474587: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-20 02:41:07.485692: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-20 02:41:07.495066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-04-20 02:41:07.503317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-04-20 02:41:07.509344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6380 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-04-20 02:41:07.830125
WARNING:tensorflow:From C:\Program Files\Python37\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/1
2019-04-20 02:41:08.893979: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library cublas64_100.dll locally
7014/7014 [==============================] - 361s 51ms/step - loss: 7.5281 - acc: 0.0983
2019-04-20 02:47:09.605253 use: 361.77512788772583
7014/7014 [==============================] - 150s 21ms/step
Train Loss: 7.395397231117259
Train Accuracy: 0.11500426618320785
1750/1750 [==============================] - 38s 22ms/step
Test Loss: 7.447124725394183
Test Accuracy: 0.10783022532281708
2019-04-20 02:50:17.627289 use: 549.7971634864807
Epoch 1/1
7014/7014 [==============================] - 360s 51ms/step - loss: 7.3600 - acc: 0.1181
2019-04-20 02:56:18.239652 use: 910.4095270633698
Epoch 1/1
7014/7014 [==============================] - 327s 47ms/step - loss: 7.3005 - acc: 0.1246
2019-04-20 03:01:45.399760 use: 1237.5696346759796
Epoch 1/1
7014/7014 [==============================] - 323s 46ms/step - loss: 7.2748 - acc: 0.1266
2019-04-20 03:07:08.461455 use: 1560.6313297748566
Epoch 1/1
7014/7014 [==============================] - 358s 51ms/step - loss: 7.2574 - acc: 0.1277
2019-04-20 03:13:07.130713 use: 1919.300588130951
Epoch 1/1
7014/7014 [==============================] - 359s 51ms/step - loss: 7.2441 - acc: 0.1286
2019-04-20 03:19:06.897505 use: 2279.067379951477
7014/7014 [==============================] - 150s 21ms/step
Train Loss: 7.25102758246338
Train Accuracy: 0.12821495325019114
1750/1750 [==============================] - 38s 22ms/step
Test Loss: 7.357601354578912
Test Accuracy: 0.11735739382489015
2019-04-20 03:22:14.971957 use: 2467.1418311595917
Epoch 1/1
7014/7014 [==============================] - 359s 51ms/step - loss: 7.2334 - acc: 0.1292
2019-04-20 03:28:16.243174 use: 2828.413049221039
Epoch 1/1
1076/7014 [===>..........................] - ETA: 5:03 - loss: 7.2268 - acc: 0.1295Traceback (most recent call last):
  File "sv4++.py", line 152, in <module>
    main()
  File "sv4++.py", line 132, in main
    model.fit_generator(generate(1001, 1241, size, step_train, r_len, words, mp, False), steps_per_epoch=step_train, epochs=1)
  File "C:\Program Files\Python37\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Program Files\Python37\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "C:\Program Files\Python37\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Program Files\Python37\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Program Files\Python37\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt

F:\code\python\hand_writing>